apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-build
spec:
  params:
    - name: IMAGE
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      args:
        [
          "--dockerfile=/workspace/source/Dockerfile",
          "--context=/workspace/source/",
          "--destination=$(params.IMAGE)",
          "--insecure",
          "--skip-tls-verify",
        ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
