default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres                # This must match the Service name in Kubernetes
  port: 5432
  username: postgres
  password: mysecretpassword    # Same as in your postgres-deployment.yml
  timeout: 5000

development:
  <<: *default
  database: rails_app_development

test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  database: rails_app_production
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>


