apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails
        image: pavithra809/rails-ai-sentiment:v3
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_HOST
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_PORT
            value: "5432"


